@startuml

title Mastermind - Public interface class diagram

class Mastermind {
    +play()
    +{static} main()
}
Mastermind *-- Game
Mastermind *-- View

class Game {
    +initialize()
    +saveProposedCombination()
    +getProposedCombinations()
    +getSecretCombination()
    +isFinished()
    +playerWins()
}
Game *-- SecretCombination
Game *-- Player

class Combination{
    +toString(): String
    +contains(Color): Boolean
}
Combination *-- "4" Color
Combination <|-- SecretCombination
Combination <|-- ProposedCombination

class ProposedCombination {
    countBlacks()
    countWhites()
}

class Player {
    +saveProposedCombination()
    +getLastProposedCombination()
    +getProposedCombinationsCount()
    +getProposedCombinations()
}
Player *-- "0..10"ProposedCombination

Enum Color {
    Red
    Blue
    Yellow
    Green
    Orange
    Purple
}


abstract class View {
    +{abstract}interact()
}
View <|-- GameView
View <|-- PlayView
View <|-- AttemptView
View --> Game
GameView ..> PlayView
GameView ..> ResumeView
GameView ..> EndView
PlayView ..> AttemptView
PlayView ..> CombinationView
CombinationView ..> Combination

class Console {
    +{static}getInstance()
    +getValidValue()
    +getLowerCaseString()
    +printAttempts()
    +printProposalResult()
    +print()
}
PlayView ..> Console
AttemptView ..> Console
ResumeView ..> Console
EndView ..> Console
CombinationView ..> Console
@enduml
